<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  // import ImgZoom from '$lib/components/image_zoom.svelte';
  // import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <h2 id="about"><a href="#about">About Abhinav Patel</a></h2>
    <p>
      Hi there! I'm Abhinav Patel, a tech enthusiast with a passion for understanding the intricate dance between
      hardware and software. While my expertise lies in web development, my true fascination lies in exploring the
      intersection of computer architecture and software engineering.
    </p>

    <p>
      My journey into the world of technology began with a simple question: how does the software I write interact with
      the hardware it runs on? This curiosity led me down a rabbit hole of discovery, from studying the fundamentals of
      computer architecture to exploring the inner workings of modern processors and memory systems.
    </p>

    <p>
      While I may not be tinkering with hardware on a daily basis, I find immense joy in unraveling the mysteries of how
      hardware and software work together to power our digital world. Whether it's diving into the intricacies of CPU
      pipelines or exploring the nuances of memory management, I'm always eager to deepen my understanding of the
      underlying principles that govern computing.
    </p>

    <p>
      Beyond the technical intricacies, I'm also passionate about sharing my knowledge and insights with others. Whether
      through writing, teaching, or engaging in meaningful discussions, I believe in the power of knowledge-sharing to
      drive innovation and inspire others to pursue their own intellectual passions.
    </p>

    <p>
      Thanks for joining me on this journey of exploration and discovery. Whether you're a fellow enthusiast or just
      curious about the inner workings of technology, I'm always eager to connect and exchange ideas. Feel free to reach
      out – together, we can unlock the secrets of the digital universe!
    </p>

    <!-- <ImgZoom src="/profile-pic.webp" alt="Abhinav Patel Profile Picture" /> -->
  </article>
</Post>
